image: Visual Studio 2017

platform:
  - x64
 
configuration:
  - Release
  - Debug

environment:
  PYTHON: "C:\\Python36-x64"

build: off

install:
  # update path to use installed pip
  - set PATH=%PYTHON%\\scripts;%PATH%
  # Install python packages
  - "%PYTHON%/Scripts/pip.exe install twine toml"

test_script:
  # test/hello
  - "%PYTHON%/python clang-build.py -d\"test/hello\" -V"
  - 'build\main.exe'
  # test/mini-project
  - "%PYTHON%/python clang-build.py -d\"test/mini-project\" -V"
  - 'build\main.exe'
  # test/mwe-toml
  - "%PYTHON%/python clang-build.py -d\"test/mwe-toml\" -V"
  - 'build\runHello.exe'
  # test/external-project
  - "%PYTHON%/python clang-build.py -d\"test/external-project\" -V"
  - 'build\myexe\runHello.exe'
  # test/lib-and-exe
  - "%PYTHON%/python clang-build.py -d\"test/lib-and-exe\" -V"
  # TODO: need to copy build/mylib/mylib.dll into exe's directory
  # - 'build\myexe\runLib.exe'